apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: demowebapi
          image: "akstrainingreg.azurecr.io/demo-webapi:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
      - name: regcred
