kind: Service
apiVersion: v1
metadata:
  name: demowebapp
spec:
  selector:
    app: frontend
    company: A
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      company: A
  template:
    metadata:
      labels:
        app: frontend
        company: A
    spec:
      containers:
        - name: demowebapp
          image: "workshoprrp.azurecr.io/demo-webapp:latest"
          imagePullPolicy: Always
          env:
            - name: ApiHost
              value: "demowebapi"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
      - name: srcred