apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowebapp
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      company: A
  template:
    metadata:
      labels:
        app: frontend
        company: A
    spec:
      containers:
        - name: demowebapp
          image: "akstrainingreg.azurecr.io/demo-webapp:latest"
          imagePullPolicy: Always
          env:
            - name: ApiHost
              value: "demowebapi"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
      - name: regcred